[mssql]
; jmeno sekce v /etc/freetds/freetds.conf
servername = ws11
database = VUT25
driver = FreeTDS
; STROJ\uzivatel (lokalni ucet) nebo DOMENA\uzivatel, bez uvozovek
uid = PC-EMVUT\EM VUT
pwd = EMvut@G13

[influx]
url = http://localhost:8086
org = org
token = WdFESJC66KUdKpRQk3PQdnWXTqDxJNN1FKDPecKM5VWVbx89gUnxnrLQp5UIJ8KZClRfTfgiIli9hnX28G6xKA==
bucket_history = history
bucket_forecast = forecast
